# -*- coding: utf-8 -*-
"""class_cesarcipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

class CesarCipher():
    def __init__(self,message,shift):
        self.message = message
        self.shift = shift
    
    def encrypt(self):
        a = ''
        for char in self.message:
            a += chr(ord(char)+ self.shift)
        return a

    def decrypt(self):
        a = ''
        for char in self.message:
            a += chr(ord(char)- self.shift)
        return a

p = CesarCipher('ashish',1).encrypt()
b = CesarCipher(p,1).decrypt()
print(p,b)