# -*- coding: utf-8 -*-
"""insert_sortedlist_recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def insert(L,x):
    """
    Insert x in L

    Arguments:
        L: list of sorted integers
        x: integer
    Return:
        result: sorted list of integers
    """
    print(L)
    
    if len(L) == 1 and x > L[0]:
        return L + [x]
    if x <= L[0]:
        return [x] + L
    else:
        return [L[0]] + insert(L[1:],x)
L = [1, 2, 3, 5]
x = 0
insert(L,x)

