# -*- coding: utf-8 -*-
"""intTOstr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def intTOstr(i):
    digits ='0123456789'

    if i == 0:
        return '0'

    result = ''
    
    while i > 0:
        result = digits[i%10] + result
        i = i // 10
    return result

intTOstr(2088889098766)

