# -*- coding: utf-8 -*-
"""logarithm_recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def logarithm(n): 
    
    if n == 1:
        return 0
    else:
        return 1 + logarithm(n/2)
logarithm(16)

def arb_log(base,num):
    if num == 1:
        return 0
    else:
        return 1 + arb_log(base, num/base)
arb_log(3,9)

