# -*- coding: utf-8 -*-
"""matrix_mult.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXM0QEkOWMZQMzyjRSUMeufT_2_ZiSQB
"""

#matrix multiplication

A = [[1,2,3], [4,1,5], [1,2,3]]
B = [[1,2,3], [0,3,1], [9,2,3]]
C = [[0,0,0], [0,0,0], [0,0,0]]


for i in range(len(A)):
  for j in range(len(B[0])):
    for k in range(len(A)):
    #i and j specifies the new entry in the C, k iterates to multiply each k th value of i th row (of A) and k th value of j th column(of B)
      

      C[i][j] = C[i][j] + A[i][k] * B[k][j]
      if k == len(A)-1:

        print(f'C{i}{j} = {C[i][j]}')

print(C)