# -*- coding: utf-8 -*-
"""nptel_pds2022hwa1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def matrixflip(m,direction):
    '''
    function matrixflip(m,d) that takes as input a 
    two dimensional matrix m and a direction d, 
    where d is either 'h' or 'v'. If d == 'h', the 
    function should return the matrix flipped horizontally. 
    If d == 'v', the function should retun the matrix 
    flipped vertically. For any other value of d, 
    the function should return m unchanged. In all cases,
    the argument m should remain undisturbed by the function.
    '''



    if direction == 'h':
        flipped = []
        for i in range(len(m)):
            l = []
            j = len(m[0])-1
            while j >= 0:
                l.append(m[i][j])
                j-=1
            flipped.append(l)
        return flipped
    


    if direction == 'v':
        flipped = []
        i = len(m)-1 #no of rows, 0 indexing
        #start from last row to first
        
        while i >= 0:
            l = []
            for j in range(len(m[0])):
                l.append(m[i][j])
            flipped.append(l)
            i -= 1
        return flipped

    return m
            

matrixflip([[1],[2],[3]],'h')

