# -*- coding: utf-8 -*-
"""1_PDS_nptel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def contracting(L):
    '''
    a function that takes as input a list of integer l 
    and returns True if the absolute difference between 
    each adjacent pair of elements strictly decreases.
    '''
    contract = True
    dif = abs(L[0]-L[1])
    #print('diff=',dif)
    for i in range(1,len(L)-1):
        #print('i=',i)
        #print(L[i],L[i+1])
        
        if abs(L[i]-L[i+1]) >= dif:
            contract = False
            break
        dif = abs(L[i]-L[i+1])

        #print('diff=', dif)


    return contract
contracting([98,21,77,35,11])