# -*- coding: utf-8 -*-
"""number_arrows.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

n = 5 # int(input())

i =1

while i<=n:
    for k in range(1,i+1):
        if k == i:
            print(k)
        else:
        
            print(k,end = ',')
    
    i = i+1

j = n-1
while j>= 1:
    for i in range(1,j+1):
        if i == j:
            print(i)
        else:
            print(i,end = ',')
    
    j = j-1

