# -*- coding: utf-8 -*-
"""oppe_mock1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

s = input()
count = 0
correct = ''
for num in s:
    if num != 'l' and num != 'o':
        correct = correct + num
    else:
        if num == 'l':
            count += 1
            correct = correct + '1'
        if num == 'o':
            count += 1
            correct = correct + '0'
if count == 0:
    print('no mistakes')
else:
    print(f'{count} mistakes',  correct, sep = '\n')