# -*- coding: utf-8 -*-
"""oppe_mock4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def exact_count(para, n):
    """
    Determine if at least one word occurs exactly n times
    
    Arguments:
        para: string
        n: integer
    Return:
        result: bool
    """
    words = para.split(' ')
    freq = dict()

    for word in words:
        if word not in freq:
            freq[word] = 1
        else:
            freq[word] += 1

    for key in freq:
        if freq[key] == n:
            return True
            break
    return False

