# -*- coding: utf-8 -*-
"""oppe_mock6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def crowded_group(scores_dataset, subject, mark_limit):
    groups = []

    for kid in scores_dataset:
        leader = kid['SeqNo']
        leader_score = kid['subject']
        one_group = [leader]
        

        for kid in scores_dataset:
            if kid['SeqNo'] != leader and (kid['subject'] - leader_score) <= mark_limit:
                one_group.append(kid['SeqNo'])
        groups.append(one_group)

    max = 0
    for l in groups:
        if len(l) > max:
            max = len(l)

    return max

def crowded_group(scores, sub, mark_limit):
    L = [ ]
    for st in scores:
        L.append(st[sub])
    L.sort()
    gsize = 1
    for i in range(len(L)):
        for j in range(i, len(L)):
            if L[j] - L[i] <= mark_limit:
                if j - i + 1 > gsize:
                    gsize = j - i + 1
    return gsize

