# -*- coding: utf-8 -*-
"""oppe_mock10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

''' 
Accept a positive integer A as input and print the dimensions of all 
rectangles with integer sides that have an area equal to A. 
Treat a square as a rectangle with equal sides. 
In each line, print the dimension of one rectangle as a pair of 
comma separated integers — a,b — such that a≤b. The rectangle with sides 
aa and bb should be printed exactly once.
 That is, (a, b) and (b, a)represent the same rectangle.
'''
area = int(input())
a=0
b=0
for i in range(1,area+1):
    if area%i == 0:
        a = i
        b = area//i
        if a>b:
            continue
        print(a,b, sep = ',')