# -*- coding: utf-8 -*-
"""oppe_mock2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

s = input().split(',')
#s = [int(x) for x in s] list comprehension
#s = list(eval(input()))

s = list(map(int, s)) #map function
mid = len(s)//2
r_sum = 0
for r in s[0:mid]:
    r_sum += r
l_sum = 0
for l in s[mid:]:
    l_sum += l
if r_sum == l_sum:
    print('balanced')
else:

    if r_sum>l_sum:
        print('right heavy')
    else:
        print('left heavy')

