# -*- coding: utf-8 -*-
"""oppe_mock7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def crowded_group(scores_dataset, subject):
    mentees = dict()

    for kid in scores_dataset:
        leader = kid['SeqNo']
        leader_score = kid['subject']
        mentees[leader] = []
        

        for kid in scores_dataset:
            if kid['SeqNo'] != leader and  (10 <= (leader_score - kid['subject']) <= 20):
                mentees[leader].append(kid['SeqNo'])

    return mentees

def mentors(scores, subject):
    L = [ ]
    for S in scores:
        L.append((S['SeqNo'], S[subject]))
    D = dict()
    assert len(L) == 50
    for i in range(len(L)):
        D[L[i][0]] = [ ]
        for j in range(len(L)):
            if i == j:
                continue
            if 10 <= L[i][1] - L[j][1] <= 20:
                D[L[i][0]].append(L[j][0])
    return D