# -*- coding: utf-8 -*-
"""oppe_mock5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def get_summary(trans):
    l = list()
    for t in trans:
        d = dict()
        d['cost'] = 0
        d['TID'] = t['TID']
        
        for item in t['Items']:
            d['cost'] += item['Price'] * item['Qty']
        l.append(d)
    return l

