# -*- coding: utf-8 -*-
"""oppe_mock8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def exactly_two(players):
    """
    Get hold of players who play exactly two sports

    Argument:
        players: dict of dicts
    Return:
        result: set of strings
    """
    
    names = set()
    for player in players:
        sum = 0
        for game in players[player]:
            sum += int(players[player][game])
        if sum == 2:
            names.add(player)

    return names

players = {
    'Karthik': {
        'Tennis': True,
        'Badminton': True,
        'Cricket': False
           },
    'Rahul': {
        'Tennis': False,
        'Badminton': False,
        'Cricket': True
    }
}

exactly_two(players)

def exactly_two(players):
    """
    Get hold of players who play exactly two sports

    Argument:
        players: dict of dicts
    Return:
        result: set of strings
    """
    pairs = [('Tennis', 'Cricket', 'Badminton'),
             ('Cricket', 'Badminton', 'Tennis'),
             ('Badminton', 'Tennis', 'Cricket')]
    names = set()
    for player in players:
        for s1, s2, s3 in pairs:
            if (players[player][s1] and
                players[player][s2] and
                (not players[player][s3])):
                names.add(player)
    return names