# -*- coding: utf-8 -*-
"""w10ppa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

class Signal():
    def __init__(self,T):
        self.state = 'red' #initial state
        self.v = 0 #initial vehicle density
        self.T = T # threshold
    
    def sense(self, arg):
        self.v = arg
    
    def update(self):
        if self.v >= self.T:
            self.state = 'green'
        else:
            self.state = 'red'
        
S = Signal(10)
S.sense(11)
S.update()
print(S.state)

