# -*- coding: utf-8 -*-
"""w10ppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

import matplotlib.pyplot as plt

def f(x):
    return 3*x - 4

x_val = []
y_val = []

for x in range(-5,6):
    x_val.append(x)
    y_val.append(f(x))
print(x_val,y_val)   
plt.plot(x_val, y_val)

def f(x):
    return x**2 + 2*x - 15

x_val = []
y_val = []

for x in range(-5,6):
    x_val.append(x)
    y_val.append(f(x))
print(x_val,y_val)   
plt.plot(x_val, y_val)

def f(x):
    return 5*(x-1)*(x-2)*(x-3)

x_val = []
y_val = []

for x in range(-5,6):
    x_val.append(x)
    y_val.append(f(x))
print(x_val,y_val)   
plt.plot(x_val, y_val)

import math
def f(x):
    return (math.e)**x

x_val = []
y_val = []

for x in range(-1,5):
    x_val.append(x)
    y_val.append(f(x))
#print(x_val,y_val)   
plt.plot(x_val, y_val)

import math
def f(x):
    return math.log(x,10)


x_val = []
y_val = []

for x in range(1,11):
    x_val.append(x)
    y_val.append(f(x))
#print(x_val,y_val)   
plt.plot(x_val, y_val)

import math
def f(x):
    return math.sin(x)


x_val = []
y_val = []

for x in range(0,361,15):
    x_val.append(x)
    y_val.append(f(x))
#print(x_val,y_val)   
plt.plot(x_val, y_val)

