# -*- coding: utf-8 -*-
"""w10ppa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

class Point():
    def __init__(self,x,y):
        self.x = x
        self.y = y

    def distance(self):
        #distance of point from origin
        d = (self.x**2 + self.y**2) ** 0.5
        return d

    ori = False
    on_x = False
    on_y = False
    def is_origin(self):
        if self.x == self.y == 0:
            ori = True
            return True
        return False

    if not ori:
        def on_xaxis(self):
            if self.y == 0:
                on_x = True

                return True
            return False
    
        def on_yaxis(self):
            if self.x == 0:
                on_y = True
                return True
            return False
    def quadrant(self):
            
        if self.x > 0 and self.y > 0:
            return 'first'

        elif self.x < 0 and self.y < 0:
            return 'third'
            
        elif self.x < 0 and self.y > 0:
            return 'second'
            
        elif self.x > 0 and self.y < 0:
            return 'fourth'


    
    def slope(self):
        if self.x != 0:
            m = self.y/self.x
            return m


p = Point(-1,-1)
print(p.distance(),p.slope(), p.on_xaxis(), p.on_yaxis(), p.quadrant(), p.is_origin())

