# -*- coding: utf-8 -*-
"""w10ppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

import matplotlib.pyplot as plt

def f(x):
    return 3*x - 4

x_val = []
y_val = []

for x in range(-5,6):
    x_val.append(x)
    y_val.append(f(x))
print(x_val,y_val)   
plt.plot(x_val, y_val)

