# -*- coding: utf-8 -*-
"""w12ppa9_ Pearson correlation coefficient.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def f(P):
    mean = sum(P) / len(P)
    return [p - mean for p in P]

def k(P):
    mean = sum(P)/len(P)
    A = [p - mean for p in P]
    return [a**2 for a in A]
    

def g(P, Q):
    return sum(P[i] * Q[i] for i in range(len(P)))

def h(x):
    return x ** 0.5
def pearson(X, Y):
    
    numer = (g(f(X),f(Y)))
    deno = h(sum(k(X)))*h(sum(k(Y)))
    return numer/deno
	

X = [float(x) for x in input().split()]
Y = [float(y) for y in input().split()]
print(f'{pearson(X, Y):.2f}')