# -*- coding: utf-8 -*-
"""w12ppa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def primes_galore(L):
    """
    Compute number of primes located at prime indices

	Argument:
    	L: list of integers
    Return:
    	result: integer
    """
    count = 0
    def check_prime(a):
        flag = True
        if a == 0 or a == 1:
            return False
        
        for i in range(2,a//2+1):
            if a % i == 0:
                flag = False
                return False
                break
                
        return flag

    for i in range(len(L)):
        if check_prime(L[i]) and check_prime(i):
            count += 1
    return count