# -*- coding: utf-8 -*-
"""w12ppa16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSpEQeErZ_jlxyowUlAJ0Rzui5u9rlQt
"""

class Profile:
    def __init__(self,username,password):
        self.username = username
        self.password = None
        self.old_passwords = []

        if self.check_password(password):
            self.password = password
            self.old_passwords.append(self.password)





    def check_password(self,password):
        alphanum = '0123456789abcdefghijklmnopqrstuvwxyz'
        b = True
        if len(password)>=7:
            if password[0].isupper():
                for i in range(1,len(password)):
                    if self.password[i] not in alphanum:
                        b = False
                        break
            else:
                b = False
        else:
            b = False

        return b


    def change_password(self, password):
        if self.check_password(password)  and password not in self.old_passwords:
            self.password = password
            self.old_passwords.append(password)

    def login(self,username, password):
        if self.username == username and self.password == password:
            print('WELCOME')
        else:
            print('INVALID')