# -*- coding: utf-8 -*-
"""w12ppa7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSpEQeErZ_jlxyowUlAJ0Rzui5u9rlQt
"""

initial = input().split(',')
k = int(input())
while k != 0:
    #print(initial)
    initial = [initial[-1]] + initial[:-1]
    k = k - 1
for i in range(len(initial)):
    if i == len(initial)-1:
        print(initial[i])
    else:
        print(initial[i], end = ',')