# -*- coding: utf-8 -*-
"""w12ppa6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSpEQeErZ_jlxyowUlAJ0Rzui5u9rlQt
"""

def encrypt(word):
    alpha = 'abcdefghijklmnopqrstuvwxyz'
    cipher = ''
    for letter in word:
        
        index = alpha.index(letter)
        cipher += alpha[25-index]
    print(cipher)
word = input()
encrypt(word)