# -*- coding: utf-8 -*-
"""w4grpa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

names = 'sachin,ramesh,rohit,priya,saina,sandeep,stella'
dob = '100,50,100,20,30,20,20'
names_l = names.split(',')
dob_l = dob.split(',')

#names_l = input().split(',')
#dob_l = input().split(',')
dob_lst = []
for dob in dob_l:
    dob_lst.append(int(dob))
print(names_l)
print(dob_lst)

common = []


for i in range(len(dob_lst)):
    l = []
    #print(0)
    
    for j in range(i+1, len(dob_lst)):
        
        if dob_lst[i] == dob_lst[j]:
            
            l = []
            l.append(names_l[i])
            l.append(names_l[j])
            l.sort()

            if len(l) == 2:
                common.append(l)
                l = []
print(common)