# -*- coding: utf-8 -*-
"""w4grpa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

def sortlist(L):
    #insertion sort
    sorted_L = []
    sorted_L.append(L[0])

    for i in range(1,len(L)):
        flag = True
        for j in range(len(sorted_L)):
            if L[i] <= sorted_L[j]:
                beforej = sorted_L[:j]
                insert = [L[i]]
                afterj = sorted_L[j:]
                sorted_L = beforej + insert + afterj
                flag = False
                break
        if flag:
            sorted_L.append(L[i])

    if len(sorted_L) % 2 == 0:
        mid = len(sorted_L)/2
        mid = int(mid)
        median = (sorted_L[mid] + sorted_L[mid - 1])/2
    else:
        mid = int(len(sorted_L)/2)
        median = float(sorted_L[mid])

    return sorted_L, median
    
    



L= [1,3,58,9,88,88,82,33,21,22,5,-1,-77]
sorted, median = sortlist(L)
print(sorted)
print(median)