# -*- coding: utf-8 -*-
"""3X3symmetricmatirx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

#check if a word is present in the string
b = input('enter a string, words separate by single space')
a = input('enter a word ')
b_list = b.split()

i = 0
count = 0
flag = False
while i < len(b_list):
  if a == b_list[i]:
    flag = True
    count += 1
  i +=1
if flag:
  print('YES')
  print(count)
else:
  print('NO')