# -*- coding: utf-8 -*-
"""w4grpa5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

'''
You are given a sequence of n points, (x_i,y_i), 1≤i≤n, in the 2-D plane as input. 
Also, you are given a point PP with coordinates (x,y). Print all points in the sequence that are nearest to P. 
If multiple points have the same least distance from P, print the points in the order of their appearance in the sequence.
'''
n = int(input())
l = []
for i in range(n):
    cord = input('input x y cordinates').split(',')
    for j in range(len(cord)):
        cord[j] = int(cord[j])
    l.append(cord)
p = []
p = (input('x y cordinate of P, comma separated: ')).split(',')
p[0], p[1] = int(p[0]), int(p[1])

min = 1000.0
nearest = []

for i in range(len(l)):

    dist = ((p[0] - l[i][0])**2 + (p[1] - l[i][1])**2)**0.5
    print(dist)

    if dist < min:
        nearest = []
        min = dist
        nearest.append(l[i])
    if dist == min and l[i] not in nearest:
        min = dist
        nearest.append(l[i])

for i in range(len(nearest)):
    print(nearest[i][0],nearest[i][1], sep = ',')

