# -*- coding: utf-8 -*-
"""w4ppa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

num = input()
a = num.split(',')
b = []
for n in a:
  b.append(int(n))

max = b[0]

for n in b:
  if n > max:
    max = n
print(max)