# -*- coding: utf-8 -*-
"""w4ppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

n = int(input())
matrix = []
l = []
for i in range(n):
  l =[]
  int_l = []

  l = input().split(' ')
  for num in l:
    int_l.append(int(num))
  matrix.append(int_l)
  
s = int(input())

for r in range(len(matrix)):
  for c in range(len(matrix[0])):
    matrix[r][c] = matrix[r][c]*s

for i in range(len(matrix)):
  for j in range(len(matrix)):
    
    if j == len(matrix)-1:
      print(matrix[i][j])
    else:
      print(matrix[i][j], end =' ')

