# -*- coding: utf-8 -*-
"""w4ppa7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

n = int(input())
i = 0
matrix=[]
row =[]
while i < n:
  row = []
  
  row = input().split(' ')
  r =[]
  for j in row:
    r.append(int(j))

  matrix.append(r)
  i += 1
print(matrix)

