# -*- coding: utf-8 -*-
"""w4ppa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

n = int(input())
l =[]
for i in range(n):
  word = input()
  l.append(word)
print(l)