# -*- coding: utf-8 -*-
"""w4ppa6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

a = input()
a_list= a.split(',')
b = len(a_list)
for i in range(-1, -(b), -1):
  print(a_list[i], end = ',')
print(a_list[0])

