# -*- coding: utf-8 -*-
"""w4ppa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

L = input().split(',')
longest = L[0]
for word in L:
    if len(word) >= len(longest):
        longest = word
print(longest)