# -*- coding: utf-8 -*-
"""w4ppa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6VeRSn04lH8PvN_tjezT9aZjTX2ZvvA
"""

n = int(input())
l = []
for i in range(1,n+1):
  l.append(i)
print(l)