# -*- coding: utf-8 -*-
"""w5grpa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFO8glTthBbuCfCatp_1vDx6QZOHLQvV
"""

def distance(word_1,word_2):

    def pos(alphabet):
        alpha = 'abcdefghijklmnopqrstuvwxyz'
        return (1 + alpha.index(alphabet))

    if len(word_1) != len(word_2):
        return -1

    sum = 0
    if len(word_1) == len(word_2):
        for i in range(len(word_1)):
            sum += abs(pos(word_1[i]) - pos(word_2[i]))

    return sum

distance('dog','cat')