# -*- coding: utf-8 -*-
"""w5grpa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFO8glTthBbuCfCatp_1vDx6QZOHLQvV
"""

def is_perfect(n):
    sum = 0
    for i in range(1,n):
        if n%i == 0:
            sum += i
    if sum == n:
        return True
    else:
        return False
is_perfect(7)