# -*- coding: utf-8 -*-
"""w5grpa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFO8glTthBbuCfCatp_1vDx6QZOHLQvV
"""

def is_magic(m):

    '''
    A n×n square matrix of positive integers is called a magic square if the following sums are equal:
    (1) row-sum: sum of numbers in every row; there are nn such values, one for each row
    (2) column-sum: sum of numbers in every column; there are nn such values, one for each column
    (3) diagonal-sum: sum of numbers in both the diagonals; there are two values
    '''
    dim = len(m)

    

    def row_sum(l):
        
        rowsum = 0
        for i in range(dim):
            rowsum += l[i]
        return rowsum




    def magic_row(m):
        
        rs = []
    
    
        for i in range(dim):
            rs.append(row_sum(m[i]))

        B = True
        for p in range(0,len(rs)-1):
            if rs[p] != rs[p+1]:
                B = False
                break
        if B:
            return rs[0]
        

     

    def magic_column(m):
        
        l = []
        colsum = []
        for r in range(len(m)):
            l = []
            for c in range(len(m)):
                l.append(m[c][r])

        colsum.append(row_sum(l))

    

        B = True
        for p in range(0,len(colsum)-1):
            if colsum[p] != colsum[p+1]:
                B = False
                break
        if B:
            return colsum[0]

    def dgnl_left(m):
        
        sum = 0
        for i in range(dim):
            for j in range(dim):
                if i == j:
                    sum += m[i][j]
        return sum

    def dgnl_right(m):
        
        sum = 0
    
        for r in range(dim):
            c = (dim-1) - r
            sum += m[r][c]
        return sum


    if dgnl_left(m) == dgnl_right(m):
        if dgnl_left(m) == magic_row(m) and magic_row(m) == magic_column(m):
            return 'YES'
        else:
            return 'NO'
    else:
        return 'NO'

m = [[4,9,2], [3,5,7], [8,1,6]]
print(is_magic(m))