# -*- coding: utf-8 -*-
"""w5grpa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFO8glTthBbuCfCatp_1vDx6QZOHLQvV
"""

def get_range(L):
    maxi = L[0]
    mini = L[0]
    for i in range(len(L)):
        if L[i] > maxi:
            maxi = L[i]
        if L[i] < mini:
            mini = L[i]
    return maxi - mini