# -*- coding: utf-8 -*-
"""w5ppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def get_column(mat,col):
    c = []
    for i in range(len(mat)):
        c.append(mat[i][col])
    return c

def get_row(mat,row):
    r = []
    for i in range(len(mat[0])):
        r.append(mat[row][i])
    return r




mat = [[1,2,3],[4,5,6]]
print(get_column(mat,2))
print(get_row(mat,1))

