# -*- coding: utf-8 -*-
"""w5ppa7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def is_empty(L):
    a = len(L)
    if a == 0:
        return True
    else:
        return False

def first(L):
    if not is_empty(L):
        return L[0]
        
def last(L):
    if not is_empty(L):
        return L[-1]

def init(L):
    if not is_empty(L):
        return L[:-1]
        
def rest(L):
    if not is_empty(L):
        return L[1:]