# -*- coding: utf-8 -*-
"""w5ppa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def maxval(a,b,c):
    max = a
    if b > max:
        max = b
    if c > max:
        max = c
    return max

maxval(10000,2,100)