# -*- coding: utf-8 -*-
"""w5ppa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def dim_equal(A,B):
    flag = False
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        flag = True
    return flag