# -*- coding: utf-8 -*-
"""w5ppa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def factorial(n):
    
    if n < 0:
        return -1
    if n == 0:
        return 1
    if n == 1:
        return 1
    else :
        return n*factorial(n-1)
n = int(input())
factorial(n)

def factor():
    n = int(input())
    if n < 0:
        return -1
    elif n == 0:
        return 1
    elif n == 1:
        return 1

    else:
        f = 1
        for i in range(1,n+1):
            f = f*i
    return f

factor()

