# -*- coding: utf-8 -*-
"""w5ppa10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def insert(L,x):
    flag = False
    for i in range(len(L)):
        if x<L[i]:
            beforei = L[:i]
            afteri = L[i:]
            beforei.append(x)
            L = beforei + afteri
            flag = True
            break
    if not flag:
        L.append(x)
    return L

L = [5,6,8,9]   
insert(L,7)