# -*- coding: utf-8 -*-
"""w6grpa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def scores(scores_dataset, subject, gender):
    marks = []
    for s in scores_dataset:
        if s['Gender'] == gender:
            marks.append((s['Name'],s[subject]))
    return marks

def get_toppers(scores_dataset, subject, gender):
    '''
    Write a function named get_toppers that accepts three arguments in this order:
    scores_dataset
    subject
    gender
    It should a return a list of the names of students who belong to the gender given
    by the argument gender ('F' or 'M') and have topped in the subject given by the argument subject. 
    As there could be multiple toppers, your output should be a list of names.
    '''
    l = []
    marks = scores(scores_dataset, subject, gender)
    max = 0
    toppers = []

    for student in marks:
        if student[1] > max:
            max = student[1]
            toppers = [student[0]]

        elif student[1] == max:
            toppers.append(student[0])

    return toppers

scores_dataset=[{'SeqNo': 1, 'Name': 'Devika', 'Gender': 'F', 'City': 'Bengaluru', 'Mathematics': 64, 'Physics': 98, 'Chemistry': 79, 'Biology': 75, 
 'Computer Science': 88, 'History': 43, 'Civics': 78, 'Philosophy': 55}, {'SeqNo': 2, 'Name': 'Dev', 'Gender': 'M', 'City': 'Bengaluru', 'Mathematics': 26, 'Physics': 100, 'Chemistry': 49, 'Biology': 65, 
 'Computer Science': 98, 'History': 73, 'Civics': 88, 'Philosophy': 75}]

print(get_toppers(scores_dataset, 'Physics', 'M'))

