# -*- coding: utf-8 -*-
"""w6grpa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def rev_list(l):
    c = -len(l)-1
    rev_l = []
    for i in range(-1,c,-1):
        rev_l.append(l[i])
        
    return rev_l

def trans(mat):
    new_row = []
    transpose = []

    for i in range(len(mat[0])):
        new_row = []
        for j in range(len(mat)):
            new_row.append(mat[j][i])
        transpose.append(new_row)

    return transpose


def rotate(mat):
    '''
    Write a function named rotate that accepts a matrix mat as argument.
    It should return a matrix that is rotated by 90 degree in the clockwise direction.
    '''
    output = []
    transpose = trans(mat)

    for i in range(len(transpose)):
        output.append(rev_list(transpose[i]))

    return output
    


M = [[1,2,3],[4,5,6]]
print(rotate(M))

