# -*- coding: utf-8 -*-
"""w6ppa6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def get_marks(scores_dataset, subject):
    marks = []
    for x in scores_dataset:
        marks.append((x['Name'], x[subject]))
    return marks