# -*- coding: utf-8 -*-
"""w6ppa10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def group_by_city(scores_dataset):
    d = {}
    for score in scores_dataset:
        if score['City'] not in d:
            d[score['City']] = []
            d[score['City']].append(score['Name'])
        else:
            d[score['City']].append(score['Name'])

    return d

def busy_city(scores_dataset):
    
    d = group_by_city(scores_dataset)
    l = []

    for city in d:
        l.append((city,len(d[city])))

    busy  = []
    max = 0
    for x in l:
        if x[1] > max:
            max = x[1]
    
    for y in l:
        if y[1] == max:
            busy.append(y[0])

    return busy
    
m = [{'Name': 'Dev',  'City': 'Bengaluru'}, {'Name': 'Drake',  'City': 'Bengaluru'},{'Name': 'Devi',  'City': 'kochi'}, {'Name': 'bryan',  'City': 'tvm'}, {'Name': 'bro',  'City': 'tvm'}]
print(busy_city(m))

