# -*- coding: utf-8 -*-
"""w6ppa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def is_key(D,key):
    if key in D:
        return True
    else:
        return False
def value(D, key):
    if key in D:
        return D[key]