# -*- coding: utf-8 -*-
"""w6ppa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def value_to_keys(D,value):
    l = []
    for x in D:
        if D[x] == value:
            l.append(x)
    return l

d ={'ashish':1446, 'aswin':1446}