# -*- coding: utf-8 -*-
"""w6ppa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def numberinwords():
    s = int(input())
    s = str(s)
    d = {'0':'zero', '1':'one','2':'two','3':'three','4':'four','5':'five','6':'six','7':'seven','8':'eight','9':'nine'}

    for x in s:
        if x in s:
            print(d[x])

numberinwords()

