# -*- coding: utf-8 -*-
"""w6gppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def real_dict():
    '''
    Accept a sequence of words as input. Create a dictionary named real_dict whose keys are the letters of the English alphabet. 
    For each key (letter), the corresponding value should be a list of words that begin with this key (letter). 
    For any given key, the words should be appended to the corresponding list in the order in which they appear in the sequence. 
    You can assume that all words of the sequence will be in lower case.
    '''
    p = input().split(',')
    d = {}

    for word in p:
        if word[0] not in d:
            d[word[0]] = []
            d[word[0]].append(word)
        else:
            d[word[0]].append(word)
    return d

print(real_dict())

