# -*- coding: utf-8 -*-
"""w6ppa7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def make_scores_dataset():
    n = int(input())
    scores_dataset = {}
    marks = []


    for i in range(n):
        scores_dataset = {}
        scores_dataset['Name'] = input()
        scores_dataset['City'] = input()
        scores_dataset['SeqNo'] = int(input())
        scores_dataset['Mathematics'] = int(input())
        scores_dataset['Physics'] = int(input())
        scores_dataset['Chemistry'] = int(input())
        marks.append(scores_dataset)
    return marks

make_scores_dataset()