# -*- coding: utf-8 -*-
"""w6ppa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDp_xCQFg55Y4auGSqR4U_y7leAamKVT
"""

def word_freq():
    seq = input()
    seq_list = seq.split(',')
    freq = {}
    for x in seq_list:
        if x not in freq:
            freq[x] = 1
        else:
            freq[x] += 1
    return freq
word_freq()

