# -*- coding: utf-8 -*-
"""w8grpa5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def ancestry(P,present,past):
    """
    w8grpa5
    A recursive function to compute the sequence of ancestors of person

    Arguments:
        P: dict, key and value are strings
        present: string
        past: string
    Return:
        result: list of strings
    """
    if present == past:
        return [present]
    else:
        l = [present]
        present = P[present]
        return l + ancestry(P,present,past)
P = {'Jahangir': 'Akbar', 'Akbar': 'Humayun', 'Humayun': 'Babur'}
present = 'Jahangir'
past = 'Babur'
ancestry(P,present,past)