# -*- coding: utf-8 -*-
"""w8grpa3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def collatz(n):
    """
    A recursive function to compute the number of calls to the Collatz function of n

    Argument:
        n: integer
        Assume that 1 < n <= 32,000
    Returns: 
        result: integer
    """
    
    if n == 1:
        return 0
    else:
        i = 1
        if n%2 == 0:
            n = n/2
        else:
            n = 3*n+1

        return i + collatz(n)
collatz(10)

