# -*- coding: utf-8 -*-
"""w8grpa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def linear(P,Q,k):
    """
    A recursive function to determine if a list is scalar multiple of the other

    Arguments:
        P: list of integers
        Q: list of integers
        k: integer
    Return:
        result: bool
    """
    if len(P) != len(Q):
        return False
    else:
        if len(P) ==1 and len(Q) == 1: #base case, it shld return the final T or F
            return (P[0] == k*Q[0])

        if (P[0] != k*Q[0]): # all other cases except base, if P[0] == k*Q[0] is T, go ahead, do nothin, if F, return F
            return False
        else:
            return linear(P[1:], Q[1:], k) # each call removes the first element of both p & Q

P = [2, 4, 6, 8]
Q = [1, 2, 3, 4]
k = 2
linear(P,Q,k)

