# -*- coding: utf-8 -*-
"""w8ppa6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def spiral_iterative(left,right,n):
    '''using loops, this works'''
    
    l = [left,right]
    for i in range(2,n+1):
        l.append( (l[i-1] + l[i-2])/2 )
    return l #[-1]
spiral_iterative(1,12,7)

def spiral_recursive(left,right,n):
    '''using recursion'''
    p0,p1 = left,right
    
    new = (p0+p1)/2
    p3 = p0
    p0 = p1
    p1 = new
    #print(new)
    
    if n <= 0:
        return p3
    else:
        return spiral_recursive(p0,p1,n-1)
    
spiral_recursive(1,12,7)

