# -*- coding: utf-8 -*-
"""w8ppa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def factorial(n): 
    if n == 1 or n==0:
        return 1
    else: 
        return n*factorial(n-1)

factorial(5)

