# -*- coding: utf-8 -*-
"""w8ppa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def triangular(n):
    '''
    a recursive function named triangular that accepts a positive integer n
    as argument and returns the sum of the first n positive integers.
    '''
    if n == 0:
        return 0
    else:
        return n+triangular(n-1)
        
triangular(5)

