# -*- coding: utf-8 -*-
"""w8ppa7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def count(L,word):
    """
    A recursive function to compute the frequency of occurrences of word in L

    Arguments:
        L: list of words
        word: string
    Return:
        result: integer
    """
    
    if len(L) == 0:
        return 0
    if L[0] == word and len(L) == 1:
        return 1
    if L[0] != word and len(L) == 1:
        return 0

    if L[0] == word:
        return 1 + count(L[1:],word)

    else:
        return 0 + count(L[1:],word)
        
L= ['good', 'string', 'good', 'again', 'good']
word = 'good'
count(L,word)

