# -*- coding: utf-8 -*-
"""w8ppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def  uniq(L):
    """
    A recursive function to get unique elements from the list
    
    Argument:
        L: list
    Return:
        result: list
    """
    
    if len(L) == 1:
        return L
    if len(L) > 1:
        p = L[0]
        L.remove(p)
        if p not in L:
            return [p] + uniq(L)
        else:
            return uniq(L)
   
L = [1, 2, 3, 2, 1, 4]
uniq(L)

