# -*- coding: utf-8 -*-
"""w8ppa10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def binary_search(L,k):
    """
    A recursive function that searches for an element k in L

    Arguments:
    	L: list
    	k: int
    Return:
    	bool
    """
    
    if len(L) == 1:
        if L[0] == k:
            return True
        else:
            return False
    else:
        mid = len(L)//2
        if L[mid] == k:
            return True
        
        if k > L[mid]:
            return binary_search(L[mid+1:],k)
        
        else:
            return binary_search(L[:mid+1],k)
L = [10, 20, 30, 40, 50]
k =20
binary_search(L,k)

