# -*- coding: utf-8 -*-
"""w9grpa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def get_freq(filename):
    """
    Extract frequency information from the file

    Argument:
        filename: string, path to file
    Return:
        result: dictionary; keys are strings, values are integers
    """
    f = open(filename, 'r')
    s = f.read().split('\n')
    freq = dict()


    for word in s:
        if word not in freq:
            freq[word] = 1
        else:
            freq[word] +=1
    return freq

