# -*- coding: utf-8 -*-
"""w9grpa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def relation(file1,file2):
    """
    Determine the relationship between two files

    Arguments:
        file1, file2: strings, paths to two files
    Return:
        string: 'Equal', 'Subset' or 'No Relation'
    """
    h1 = open(file1,'r')
    h2 = open(file2,'r')

    l1 = h1.read().split('\n')
    l2 = h2.read().split('\n')

    subset = True
    if len(l1) < len(l2):
        for i in range(len(l1)):
            if l1[i] != l2[i]:
                subset = False
                break
        if subset == True:
            return 'Subset'

    equal = True

    if len(l1) == len(l2):
        for i in range(len(l1)):
            if l1[i] != l2[i]:
                equal = False
                break
        if equal == True:
            return 'Equal'
    
    if not(equal and subset):
        return 'No Relation'

