# -*- coding: utf-8 -*-
"""w9ppa8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def improvement(filename):
    f = open(filename,'r')
    count = 0
    f.readline()
    for line in f:
        Name,Gender,CT,Python,PDSA  = line.split(',')
        ct = int(CT)
        py = int(Python)
        pdsa = int(PDSA)

        if ct < py < pdsa:
            count += 1
    return count