# -*- coding: utf-8 -*-
"""w9ppa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7_M042zwV55DlTaoCavvHK0c0t9-2UP
"""

def readline(filename,n):

    """
    Read the nth line of the file

    Argument:
        filename: string, name of the file to be read
    Return:
        string: return nth line of the file
    """
    
    f = open(filename, 'r')
    stuff = f.readlines()
    if n<= len(stuff): # in files line are counted from 1. total lines in file = len(stuff)
        return stuff[n-1] #in string its 0 based index, so n the line in file will be stuff[n-1]
    return None