# -*- coding: utf-8 -*-
"""w9ppa4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def get_dict(filename):
    """
    Convert the contents of the file into a dict

    Argument:
        filename: string, path of the file
    Return:
        result: dict; keys are strings, values are integers
    """
    f = open(filename,'r')
    d = dict()
    f.readline()
    for line in f:
        #line.strip()
        name, age = line.split(',')
        d[name] = int(age)
    return d