# -*- coding: utf-8 -*-
"""w9ppa7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def add_period(filename):
    """
    Add a period at the end of each line

    Argument:
        filename: string; path of the file
    Return:
        None
    """
    f = open(filename,'r')
    g = open('out.txt','w')

    for line in f:
        line = line.strip()
        g.write(line + '.' + '\n')
        
    f.close()
    g.close()