# -*- coding: utf-8 -*-
"""w9ppa5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def get_matrix(filename):
    """
    Convert the contents of the file into a matrix

    Argument:
        filename: string
    Return:
        matrix: list of lists
    """
    f = open(filename, 'r')
    M = []

    for line in f:
        l = line.split(',')
        lst = [int(x) for x in l]
        M.append(lst)
    return M