# -*- coding: utf-8 -*-
"""w9ppa10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def number_grid(m, n):
    """
    Write a number grid to a file

    Arguments:
        m, n: positive integers
    Return:
        None
    """
    f = open('numgrid.csv' ,'w')

    s = 0

    
        
    for i in range(m):
        if s <= m*n:
        
            
        
            for j in range(n):
                s = s + 1
                if j == n-1:
                    f.write(str(s))
                    f.write('\n')
                else:
                    f.write(str(s))
                    f.write(',')
    f.close()