# -*- coding: utf-8 -*-
"""w9ppa9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def extract_lines(filename):
    """
    Get all males who have scored at least 70 marks in Python
    
    Argument:
        filename: string
    Return:
        None
    """
    f = open(filename, 'r')
    g = open('python.csv','w')
    header = f.readline()
    g.write(header)

    for line in f:
        SeqNo, Name,Gender,CT,Python,PDSA  = line.split(',')
        

        if Gender == 'M' and int(Python) >= 70:
            g.write(line)