# -*- coding: utf-8 -*-
"""w9ppa6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def write_AP(a_1, d, n):
    """
    Write the AP to a file

    Arguments:
        a_1: first term, integer
        d: common difference, integer
        n: number of terms, integer
    Return:
        None
    """
    f = open('out.txt', 'w')
    f.write(str(a_1))
    f.write('\n')
    a = a_1

    for i in range(2,n+1):
        a_i = a + d
        n = str(a_i)
        
        f.write(n)
        f.write('\n')
        a = a_i
    f.close()

