# -*- coding: utf-8 -*-
"""w9ppa11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def collection_to_file(scores_dataset):
    """
    Convert a collection to a file

    Argument:
        scores_dataset: list of dicts
    Return:
        None
    """
    f = open('scores.csv','w')
    f.write('SeqNo,')
    f.write('Name,')
    f.write('Gender,')
    f.write('City,')
    f.write('Mathematics,')
    f.write('Physics,')
    f.write('Chemistry\n')
    sd = scores_dataset
    

    for i in range(len(sd)):
        
        if i == len(sd)-1:
            f.write(f'{sd[i]["SeqNo"]},')
            f.write(f'{sd[i]["Name"]},')
            f.write(f'{sd[i]["Gender"]},')
            f.write(f'{sd[i]["City"]},')
            f.write(f'{sd[i]["Mathematics"]},')
            f.write(f'{sd[i]["Physics"]},')
            f.write(f'{sd[i]["Chemistry"]}')
            
        else:
            f.write(f'{sd[i]["SeqNo"]},')
            f.write(f'{sd[i]["Name"]},')
            f.write(f'{sd[i]["Gender"]},')
            f.write(f'{sd[i]["City"]},')
            f.write(f'{sd[i]["Mathematics"]},')
            f.write(f'{sd[i]["Physics"]},')
            f.write(f'{sd[i]["Chemistry"]}\n')
    f.close()

