# -*- coding: utf-8 -*-
"""w9ppa11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTf40H_w8PbZPLGnuNFsmXYe68Q_fzN0
"""

def collection_to_file(scores_dataset):
    """
    Convert a collection to a file

    Argument:
        scores_dataset: list of dicts
    Return:
        None
    """
    f = open('scores.csv', 'w')
    f.write('SeqNo,Name,Gender,City,Mathematics,Physics,Chemistry\n')
    for stud in scores_dataset:
        sno = stud['SeqNo']
        name = stud['Name']
        gender = stud['Gender']
        city = stud['City']
        ma = stud['Mathematics']
        phy = stud['Physics']
        chm = stud['Chemistry']
        line = f'{sno},{name},{gender},{city},{ma},{phy},{chm}\n'
        if stud['SeqNo'] == scores_dataset[-1]['SeqNo']:
            line = line.strip()
        f.write(line)
    f.close()